spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:memo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:memo}

  jpa:
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    de.tum.cit.memo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
